name: "Rust Hello World Sample"

on:
  push:
    branches: [ main ]
    paths:
      - "golang/mymodule/**"
      - ".github/workflows/golang-mymodule.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "golang/mymodule/**"
      - ".github/workflows/golang-mymodule.yml"

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        go: [ '1.14', '1.13' ]
    name: Build MyModule Go ${{ matrix.go }} sample
    env:
      working-directory: ./golang/mymodule
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: go build . 
        working-directory: ${{ env.working_directory }}
      - uses: actions/upload-artifact@v2
        with:
          name: webserver-binary
          path: ${{ env.working_directory }}/webserver.exe