name: "Go Web Server Sample"

on:
  push:
    branches: [ main ]
    paths:
      - "golang/mymodule/**"
      - ".github/workflows/golang-mymodule.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "golang/mymodule/**"
      - ".github/workflows/golang-mymodule.yml"

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        go: [ '1.15', '1.14', '1.13' ]
    name: Build Webserver Sample for Go ${{ matrix.go }}
    env:
      working-directory: ./golang/mymodule
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go build -o webserver.exe . 
        working-directory: ${{ env.working-directory }}
      - uses: actions/upload-artifact@v2
        with:
          name: webserver-binary
          path: ${{ env.working-directory }}/webserver.exe