name: "Rust Hello World Sample"

on:
  push:
    branches: [ main ]
    paths:
      - "rust/hello-world/**"
      - ".github/workflows/rust-helloworld.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "rust/hello-world/**"
      - ".github/workflows/rust-helloworld.yml"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --manifest-path rust/hello-world/cargo.toml
    - name: Run
      run: cargo run --verbose --manifest-path rust/hello-world/cargo.toml